Fix a likely dedicated server crash involving keybinds.
Keybinds are a client concept; the server doesn't know about them, and
attempts to use them on the server will cause `NoClassDefFoundError`s
(or whatever `Error`/`Exception` the JVM feels like throwing). Instead,
the configuration tool now has different modes which can be cycled
through by shift-right-clicking. (Also the 'show details' keybind was
removed from the configuration tool since it didn't seem very useful to
me, and the tooltip method *is* available and used on both sides,
contrary to earlier versions of Minecraft.)

Also fix redstone-controlled blocks not updating correctly when
inverting the redstone state.